version: '4'
services:
   web:
    build: .
    container_name: "semantic-similarity-container"
    command: sh -c "uvicorn app:app --reload --port=8000 --host=0.0.0.0"
    ports:
        - 8000:8000
         